export const categoryList = [
    {
        id: 1,
        name: "Images & Sound",
        img: "https://eptummers.nl/media/tailoredslider_media/2/Beeld-geluid_2.png",
    },
    {
        id: 2,
        name: "Computers & Tablets",
        img: "https://eptummers.nl/media/tailoredslider_media/2/Computers-tablets.png",
    },
    {
        id: 3,
        name: "Household & Living",
        img: "https://eptummers.nl/media/tailoredslider_media/2/huishouden-wonen.png",
    },
    {
        id: 4,
        name: "Kitchen",
        img: "https://eptummers.nl/media/tailoredslider_media/2/Keuken_1.png",
    },
    {
        id: 5,
        name: "Sports & Care",
        img: "https://eptummers.nl/media/tailoredslider_media/2/scheerhorloge.png",
    },
];

export const subCategoryList = [
    {
        id: 1,
        catId: 1,
        name: "Televisies",
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/televisies.png",
    },
    {
        id: 2,
        catId: 1,
        name: "Televisie accessoires",
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/web_version-5858450_tvm5845_product_image_black-noshadow.png",
    },
    {
        id: 3,
        catId: 1,
        name: "Home cinema",
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/homecinema.jpg"
    },
    {
        id: 4,
        catId: 1,
        name: "Speakers",
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/speakers.jpg",
    },

    {
        id: 5,
        catId: 2,
        name: "Laptops",
        img: "https://eptummers.nl/media/wysiwyg/category/computers-tablets/laptop.jpg",
    },
    {
        id: 6,
        catId: 2,
        name: "tablets",
        img: "https://eptummers.nl/media/wysiwyg/category/computers-tablets/tablets.jpg",
    },
    {
        id: 7,
        catId: 2,
        name: "desktops",
        img: "https://eptummers.nl/media/wysiwyg/category/computers-tablets/desktop.jpg",
    },
    {
        id: 8,
        catId: 2,
        name: "printers",
        img: "https://eptummers.nl/media/wysiwyg/category/computers-tablets/printers.jpg",
    },

    {
        id: 9,
        catId: 3,
        name: "Washing machines",
        img: "https://eptummers.nl/media/wysiwyg/category/huishouden-wonen/wasmachines.jpg",
    },
    {
        id: 10,
        catId: 3,
        name: "Vacuum cleaners",
        img: "https://eptummers.nl/media/wysiwyg/category/huishouden-wonen/stofzuigers.jpg",
    },
    {
        id: 11,
        catId: 3,
        name: "SmartHome",
        img: "https://eptummers.nl/media/wysiwyg/category/huishouden-wonen/smarthome.jpg",
    },
    {
        id: 12,
        catId: 3,
        name: "Safety",
        img: "https://eptummers.nl/media/wysiwyg/category/huishouden-wonen/Rookmelder.jpg",
    },
    {
        id: 13,
        catId: 4,
        name: "Freezers",
        img: "https://eptummers.nl/media/wysiwyg/category/keuken/vriezers.jpg",
    },
    {
        id: 14,
        catId: 4,
        name: "Dishwashers",
        img: "https://eptummers.nl/media/wysiwyg/category/keuken/vaatwassers.jpg",
    },
    {
        id: 15,
        catId: 5,
        name: "Shave",
        img: "https://eptummers.nl/media/wysiwyg/category/sport-verzorging/scheren.jpg",
    },


];

export const productList = [
    {
        id: 1,
        subCatId: 1,
        name: "QLED TVs ",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/MicrosoftTeams-image_3_.png",
        description: "good dmsof dmslkmfs fmoksdmfsd",
    },
    {
        id: 2,
        subCatId: 1,
        name: "OLED TVs",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/wysiwyg/category/beeld-geluid/MicrosoftTeams-image_4_.png",
    },
    {
        id: 3,
        subCatId: 1,
        name: "Phillips",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/wysiwyg/Philips_2.jpg",
    },
    {
        id: 4,
        subCatId: 2,
        name: "SonOne For All Samsung remote controly",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/o/n/one-for-all-afstandsbediening-samsung-urc4910.png",
    },

    {
        id: 5,
        subCatId: 2,
        name: "Hirschmann Fekab ​Coax Antenna Cable 1.5 meters",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/8/1/811126_1.png",
    },
    {
        id: 6,
        subCatId: 3,
        name: "Google Chromecast Google TV",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/f/e/fee_786_587_png_5.webp",
    },
    {
        id: 7,
        subCatId: 3,
        name: "Samsung Q-series Soundbar HW-Q800C (2023)",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: 'https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/s/a/samsung-q-series-soundbar-hw-q800c-2023.jpg',
    },
    {
        id: 8,
        subCatId: 4,
        name: "Denon Home 150 Zwart",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/d/e/denon-home-150-multi-room-speaker.jpg"
    },

    {
        id: 9,
        subCatId: 5,
        name: "Lenovo IdeaPad 3 82KU01LGMH Laptop",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/0/1/0196119905463-image-01-20230213122553.webp",
    },
    {
        id: 10,
        subCatId: 5,
        name: "Lenovo IdeaPad 33342",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/0/1/0196119905463-image-03-20230213122600.webp",
    },
    {
        id: 11,
        subCatId: 6,
        name: "Samsung Galaxy Tab A8 WiFi 32GB Rose Goud",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/2/0/2004840848.png",
    },
    {
        id: 12,
        subCatId: 6,
        name: "Samsung Galaxy Tab A8 WiFi 16GB",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/2/0/2004840844.png",
    },
    {
        id: 13,
        subCatId: 6,
        name: "Samsung Galaxy Tab A8 WiFi 16GB",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/2/0/2004840844.png",
    },
    {
        id: 14,
        subCatId: 7,
        name: "MSI Cubi 5 10M-414EU",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/2/0/2004902762.jpeg",
    },
    {
        id: 15,
        subCatId: 8,
        name: "Epson Expression Premium XP-6105",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/e/p/epson_1_1.jpg",
    },
    {
        id: 16,
        subCatId: 8,
        name: "Epson Expression ",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/e/p/epson_5_1.jpg",
    },
    {
        id: 17,
        subCatId: 9,
        name: "Samsung WW80T734AWH/S2 ",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/s/a/samsung_ww80t734awh_quickdrive_7000_serie_wasmachine.jpg",
    },
    {
        id: 18,
        subCatId: 9,
        name: "Samsung GalaxyWW80T734AWH",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/s/a/samsung_ww80t734awh_quickdrive_7000_serie_wasmachine.jpg",
    },
    {
        id: 19,
        subCatId: 10,
        name: "AEG AB61C3CR",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/r/e/remote.jpg_4_3.png",
    },
    {
        id: 20,
        subCatId: 10,
        name: "Samsung2 AEG AB61C3CR2344",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/r/e/remote.jpg_4_3.png",
    },
    {
        id: 21,
        subCatId: 11,
        name: "Google Nest Learning Thermostat V3 Premium Silver",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/1/3/1366015.webp",
    },
    {
        id: 22,
        subCatId: 11,
        name: "Google Nest Learning Thermostat V3 Premium Silver",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/1/3/1366015.webp",
    },
    {
        id: 23,
        subCatId: 12,
        name: "Samsung Safety",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/wysiwyg/category/huishouden-wonen/Rookmelder.jpg",
    },
    {
        id: 24,
        subCatId: 13,
        name: "Bosch GSN58EWCV 21q",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/m/c/mcsa03100585_j3999_2416843_gsn58ewdv_def.webp",
    },

    {
        id: 25,
        subCatId: 13,
        name: " GSN58EWCV 21q2",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/m/c/mcsa03100585_j3999_2416843_gsn58ewdv_def.webp",
    },
    {
        id: 26,
        subCatId: 14,
        name: "DishwashersB",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/wysiwyg/category/keuken/vaatwassers.jpg",
    },
    {
        id: 27,
        subCatId: 14,
        name: "DishwashersB W2425647",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/wysiwyg/category/keuken/vaatwassers.jpg",
    },
    {
        id: 28,
        subCatId: 15,
        name: "Phillips S1333/41",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/s/1/s1333_41_rtp_global_001_3_1.jpg",
    },
    {
        id: 29,
        subCatId: 15,
        name: "Philips MG3740/15",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/p/h/philips_trim_1_1.jpg",
    },
    {
        id: 30,
        subCatId: 15,
        name: "Philips123 MG37402121/15",
        price: 1200,
        rating: 4.3,
        quantity: 10,
        sell: false,
        description: "good dmsof dmslkmfs fmoksdmfsd",
        img: "https://eptummers.nl/media/catalog/product/cache/7596907dda960431c9a022f2d3b01a28/1/4/14-series-3000-baardtrimmer.jpg",
    },
];

export const userLoginCredential = [
    { id: 1, username: "Dhruv", password: "123", active: false },
    { id: 2, username: "admin", password: "123456", active: false },
];